version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.37
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/project/
      - run:
          name: "Test Website"
          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore
      - run:
          name: "Install NodeJS"
          command: apk update && apk add nodejs
      - run:
          name: "Install and initialize Firebase CLI"
          command: npm install -g firebase-tools
      - run:
          name: "Preparation"
          command: mv firebase.json public/ && mv .firebaserc public/ && cd public
      - run:
          name: "Deploy"
          command: firebase deploy --token "$FIREBASE_TOKEN"
