defaults: &defaults
  docker:
    - image: node:10.15.0-alpine
  working_directory: ~/project

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: inductor-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: "Build environment"
          command: npm run install
      - run:
          name: "Run lint"
          command: npm run lint
      - run:
          name: "Build website"
          command: "npm run build"
      - save_cache:
          key: inductor-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
          - "~/project/inductor.me/node_modules"
  deploy:
    <<: *defaults
    steps:
      - checkout



workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - deploy:
        requires:
          - build
        filters:
          branches:
            only: master
